"""
Django settings for the project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import datetime
from pathlib import Path
import os
import socket
from django.contrib.messages import constants as messages
from pathlib import Path
import os, json
from dotenv import dotenv_values


def _smart_cast(value: str):
    s = value.strip()

    # boolean
    if s.lower() in ("true", "1", "yes", "on"):
        return True
    if s.lower() in ("false", "0", "no", "off"):
        return False

    # int
    try:
        return int(s)
    except ValueError:
        pass

    # float
    try:
        return float(s)
    except ValueError:
        pass

    # lista simples por vírgula (se não for JSON explícito)
    if "," in s and not (s.startswith("{") or s.startswith("[")):
        return [item.strip() for item in s.split(",")]

    # JSON (dict/list/null/true/false/num/str)
    try:
        return json.loads(s)
    except Exception:
        return s  # string pura


START_TIME = datetime.datetime.now()
APP_STARTED = str(int(datetime.datetime.now().timestamp()))
VERSION = 'v0.1'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = "/app/data"

# .env UNICO do repositorio: a raiz manda (mesmo arquivo dos docker-compose).
# Dentro do container o backend e montado em /app e o compose injeta tudo via
# env_file, entao o arquivo pode nao existir — dai o fallback para backend/.env.
ENV_FILE = next(
    (p for p in (BASE_DIR.parent / ".env", BASE_DIR / ".env") if p.is_file()),
    BASE_DIR.parent / ".env",
)

# Segredos GERADOS no primeiro boot (SECRET_KEY) — nao sao configuracao,
# ficam no volume de dados. Ver asm_simulator/startup.py:create_default_dot_env().
SECRETS_ENV_FILE = Path(DATA_DIR) / ".env"

# Precedencia: os.environ (SO/compose) > .env da raiz > segredos gerados.
_file_env = {}
for _source in (SECRETS_ENV_FILE, ENV_FILE):  # o ultimo sobrescreve o anterior
    _file_env.update({
        k: v for k, v in (dotenv_values(_source) or {}).items()
        if k and v is not None
    })

for _key, _val in _file_env.items():
    os.environ.setdefault(_key, _val)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pk+@s=gxiu_v_z!a@8(b0d6l!j28amk_@)jg54f8le^ma99pfy'

# SECURITY WARNING: don't run with debug turned on in production!
# O padrao do sistema e DEBUG=False — ligar exige acao explicita no ambiente.
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = ['*']


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# EN e o padrao do sistema e o fallback de toda traducao (ver asm_simulator/i18n.py).
USE_I18N = True
USE_TZ = True
LANGUAGE_CODE = 'en'
TIME_ZONE = 'America/Sao_Paulo'

DEFAULT_LANGUAGE = 'en'
SUPPORTED_LANGUAGES = ['en', 'pt-br']

# 1) Valores do(s) arquivo(s) .env ja carregados acima
_env = _file_env


def _is_raw_string_setting(key: str) -> bool:
    """Segredos e chaves NUNCA passam pelo _smart_cast.

    O _smart_cast transforma qualquer string com virgula em lista (e digitos em
    int, etc.), e uma SECRET_KEY sorteada contendo virgula viraria ``list``.
    Segredo e sempre texto opaco.
    """
    return key.endswith((
        "SECRET", "SECRET_KEY", "PASSWORD", "PASSPHRASE", "TOKEN", "KEY", "KEY_PATH",
    ))


# 2) Promove as variáveis MAIÚSCULAS a settings do módulo.
#    O valor efetivo vem de os.environ (SO/compose manda mais que o arquivo);
#    o .env só entra como default — ver o setdefault feito junto ao BASE_DIR.
for key, val in (_env or {}).items():
    if not key or not key.isupper():
        continue
    raw = os.environ.get(key, val)
    globals()[key] = raw if _is_raw_string_setting(key) else _smart_cast(raw)

# Automatically add the current machine's local IP address to ALLOWED_HOSTS
try:
    hostname = socket.gethostname()
    local_ip = socket.gethostbyname(hostname)
    if local_ip not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(local_ip)
except Exception:
    pass

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'rest_framework',
    'corsheaders',
    'django_filters',

    'asm_simulator'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Projeto publico: o /admin/ entra sempre como o usuario padrao.
    'asm_simulator.middleware.AdminAutoLoginMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite e o banco do projeto. O arquivo fica no volume de dados (DATA_DIR),
# junto dos segredos gerados no primeiro boot — assim ele sobrevive ao
# recriar o container e sai do caminho do bind mount do codigo.
SQLITE_PATH = Path(os.environ.get('SQLITE_PATH', '') or (Path(DATA_DIR) / 'db.sqlite3'))
SQLITE_PATH.parent.mkdir(parents=True, exist_ok=True)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(SQLITE_PATH),
        'OPTIONS': {
            # WAL + timeout: o uwsgi serve varios workers no mesmo arquivo e,
            # no modo padrao, um write concorrente devolve "database is locked".
            'init_command': 'PRAGMA journal_mode=WAL;',
            'timeout': 20,
        },
    }
}


# Django admin — unica area com nocao de usuario. O middleware
# AdminAutoLoginMiddleware autentica ADMIN_USERNAME automaticamente.
ADMIN_URL = os.environ.get('ADMIN_URL', 'admin').strip('/')
ADMIN_USERNAME = os.environ.get('ADMIN_USERNAME', 'admin').strip()

USE_THOUSAND_SEPARATOR = True

SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_EXPIRE_SECONDS = 60 * 60  # 60 minutos
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'  # Usado para dev
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # usado em produção

if DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'asm_simulator', 'static')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',  # <-- troca 'error' por 'danger'
}

# Reverse proxy
# O nginx deste projeto serve HTTP puro. Ainda assim confiamos em
# X-Forwarded-Proto/-Host: se um proxy upstream (CDN, load balancer) terminar
# o TLS, request.is_secure()/request.scheme e todo link absoluto refletem o
# esquema externo em vez do HTTP deste hop.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Sem TLS proprio, os cookies nao podem ser marcados Secure — o navegador
# simplesmente nao os enviaria de volta por HTTP, e o admin nunca autenticaria.
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# CSRF trusted origins (scheme://host) — necessario quando a app e alcancada
# por um dominio/porta diferente do que o Django enxerga no Host.
_csrf_trusted = os.environ.get('CSRF_TRUSTED_ORIGINS', '').strip()
if _csrf_trusted:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted.split(',') if o.strip()]

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # Sem SECURE_SSL_REDIRECT nem HSTS: este deploy e HTTP por decisao de
    # projeto, e ligar qualquer um dos dois derrubaria o proprio acesso.

CRONJOBS = [
    #('* * * * *', 'asm_simulator.cron.mailer'),
]

# Django REST Framework — API 100% publica, sem autenticacao.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# CORS
CORS_ALLOW_CREDENTIALS = True
_cors_origins = os.environ.get('CORS_ORIGINS', 'http://localhost:3000')
if _cors_origins.strip() == '*':
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]

# Branding — nome/dominio do produto, configuraveis por ambiente
BRAND_NAME = os.environ.get('BRAND_NAME', 'ASMSimulator')
BRAND_DOMAIN = os.environ.get('BRAND_DOMAIN', 'asmsimulator.com.br')
BRAND_CONTACT_EMAIL = os.environ.get('BRAND_CONTACT_EMAIL', f'contato@{BRAND_DOMAIN}')

# Email / SMTP
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'{BRAND_NAME} <noreply@{BRAND_DOMAIN}>')

# ---------------------------------------------------------------------------
# Logging — SEMPRE para o stdout/stderr do processo (docker logs)
# ---------------------------------------------------------------------------
# Sem esta configuracao o Django cai no DEFAULT_LOGGING, cujo handler de console
# tem o filtro ``require_debug_true``: com DEBUG=False (o padrao do projeto)
# nada e emitido, e os loggers da aplicacao ("asm_simulator", "ASMSimulator") ficam
# sem handler nenhum. Aqui o console e incondicional: em container, log que nao
# vai para o stdout simplesmente nao existe.
LOG_LEVEL = (os.environ.get('LOG_LEVEL', 'INFO') or 'INFO').strip().upper()
DJANGO_LOG_LEVEL = (os.environ.get('DJANGO_LOG_LEVEL', LOG_LEVEL) or LOG_LEVEL).strip().upper()
# Requisicoes HTTP do runserver/uwsgi sao ruidosas; ligue com SQL_LOG_LEVEL=DEBUG.
SQL_LOG_LEVEL = (os.environ.get('SQL_LOG_LEVEL', 'WARNING') or 'WARNING').strip().upper()

LOGGING = {
    'version': 1,
    # Nao desabilita loggers ja criados no import das settings/apps.
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        # stdout (nao stderr): o docker captura os dois, mas o stdout mantem a
        # ordem em relacao aos echos do entrypoint e ao banner do bootstrap.
        'console': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'standard',
            'level': 'DEBUG',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': SQL_LOG_LEVEL,
            'propagate': False,
        },
        # Tracebacks de 500 no stdout — sem isto o Django so tentaria o
        # AdminEmailHandler, que em container nao chega a lugar nenhum.
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Loggers da aplicacao: "asm_simulator.*" (getLogger(__name__)) e o nome
        # legado "ASMSimulator" usado por mailer.py/handlers.py.
        'asm_simulator': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'ASMSimulator': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}
