# Generated by Django 5.2.3 on 2026-08-25 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('folder', 'Folder'), ('file', 'File')], default='file', max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('source', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='asm_simulator.librarynode')),
            ],
            options={
                'verbose_name': 'Library node',
                'verbose_name_plural': 'Library nodes',
                'ordering': ['name'],
            },
        ),
    ]
